### ISSUE TITLE
Stickers cannot be used from iOS mobile device

### ISSUE THREAD

**Issue by elksson** [OfficeDev/microsoft-teams-stickers-app#15]
Is there a way to make this application supported on iOS Teams app? It is great that we have custom stickers now but none of our first line workers are able to use them since they use iOS tablets, and iOS phones.

**Comment by clearab** [comment]
Support for Messaging Extensions (including the Stickers template) on mobile is a work in progress, and should be available soon. When that happens we'll update the template to make sure that it works well on mobile.

**Comment by elksson** [comment]
Awesome Thanks @clearab for the clarification.

**Comment by celadyn** [comment]
@clearab Any updates on this?
