### ISSUE TITLE
Documentation how to modify sticker administrators is vague. 

### ISSUE THREAD

**Issue by elksson** [OfficeDev/microsoft-teams-stickers-app#16]
The template app documentation mentions that you can modify the UPN’s which are allowed to modify the available stickers, however it does not mention how this UPN’s can be modified.

**Comment by nishandi** [comment]
> The template app documentation mentions that you can modify the UPN’s which are allowed to modify the available stickers, however it does not mention how this UPN’s can be modified.

Thank you for reporting this. I will add screenshots to the wiki to make it more readable here. Here is where you can go to modify the UPNs (you'd have to go to Azure portal and navigate to the relevant app service): 
![image](https://user-images.githubusercontent.com/46006849/57814232-e0c5cc80-7727-11e9-8f86-f000e4b76f17.png)
![image](https://user-images.githubusercontent.com/46006849/57814257-0226b880-7728-11e9-861e-d5c7a6293572.png)
