### ISSUE TITLE
Admin consent required for configuration app

### ISSUE THREAD

**Issue by ilantz** [OfficeDev/microsoft-teams-stickers-app#18]
I believe we should document the consent part, most organizations restrict approving new applications to their AD Tenant. I've cloned the wiki and edited it here https://github.com/ilantz/microsoft-teams-stickers-app/wiki/Deployment-guide

**Comment by aosolis** [comment]
@ilantz Thanks for the suggestion-- we will include it in the wiki.

**Comment by aosolis** [comment]
Added to the troubleshooting page here: 
https://github.com/OfficeDev/microsoft-teams-stickers-app/wiki/Troubleshooting#1-signing-in-to-the-configuration-app-is-blocked-because-tenant-admin-consent-is-required
