### ISSUE TITLE
sideload App error

### ISSUE THREAD

**Issue by sfour** [OfficeDev/microsoft-teams-stickers-app#22]
When I tried to load the app, receiving following error,

<img width="587" alt="Screen Shot 2019-06-17 at 6 04 57 PM" src="https://user-images.githubusercontent.com/2275098/59646192-aab2a880-912a-11e9-8ac1-532ec9a0f9ce.png">

Please advise

Thanks

Joe

**Comment by MattSFT** [comment]
Did you copy the error details to clipboard? If so, can you paste them here?

**Comment by sfour** [comment]
Error: An error occurred while parsing the manifest.json file; String 'zenlayer.com' does not match regex pattern '^[Hh][Tt][Tt][Pp][Ss]?://'. Path 'developer.websiteUrl', line 9, position 36.; String 'zenlayer.com' does not match regex pattern '^[Hh][Tt][Tt][Pp][Ss]?://'. Path 'developer.privacyUrl', line 10, position 36.; String 'zenlayer.com' does not match regex pattern '^[Hh][Tt][Tt][Pp][Ss]?://'. Path 'developer.termsOfUseUrl', line 11, position 39.

**Comment by MattSFT** [comment]
All of those urls must start with https:// .

**Comment by sfour** [comment]
Got it, Thanks. Working now
