### ISSUE TITLE
Step 4: Add your custom stickers

### ISSUE THREAD

**Issue by LindaSchaar** [OfficeDev/microsoft-teams-stickers-app#32]
Hello All,

When I proceed with this step:
Go to the configuration app, which is at https://[BaseResourceName]-config.azurewebsites.net. For example, if you chose “contosostickers” as the base name, the configuration app will be at https://contosostickers-config.azurewebsites.net.

When prompted, log in as one of the users that you specified in “Config Admin UPN List”.

I received this Error:
This site can’t be reached

The webpage at https://stickersvztest-config.azurewebsites.net/ might be temporarily down or it may have moved permanently to a new web address.
ERR_TUNNEL_CONNECTION_FAILED

Does anyone know the solution?

Alya

**Comment by nishandi** [comment]
hi @LindaSchaar , was your deployment successful (you can check it in Azure portal)? Also check out the troubleshooting page for common error scenarios.

**Comment by LindaSchaar** [comment]
Hi @nishandi, no it was nog succesfull. At step 6 to upload manifest.json we receive this error:
Error while extracting package: Please ensure there are no folders in your app package and that your app package contains only the manifest.json and the two required icon files at its root level. For an easier experience creating your app package, install <a href="https://teams.microsoft.com/l/app/0c5cfdbb-596f-4d39-b557-5d9516c94107" target="_blank">App Studio</a> from the Teams Store.

Do you know what this means?
