### ISSUE TITLE
error while uploading manifest.json

### ISSUE THREAD

**Issue by LindaSchaar** [OfficeDev/microsoft-teams-stickers-app#33]
Hi @nishandi, At the last step 6 I receive an error while uploading manifest.json. The installation was not succesfull. We receive this error:
Error while extracting package: Please ensure there are no folders in your app package and that your app package contains only the manifest.json and the two required icon files at its root level. For an easier experience creating your app package, install App Studio from the Teams Store.

Do you know what this means?

**Comment by nishandi** [comment]
Hi @LindaSchaar, that could be if the files were not zipped at top level (meaning there should not be any nested folders/files in the zip). Can you check?

**Comment by LindaSchaar** [comment]
Hi @nishandi, Yes the files are zipped at top level, my colleagues checked. Can it be a bug?

**Comment by LindaSchaar** [comment]
Hi @nishandi, Yes the files are zipped at top level, my colleagues checked. Can it be a bug?

**Comment by LindaSchaar** [comment]
Hi @nishandi,

We find the issue, there was a folder named package in the zip. And the zipped file was ook package. We changed this and it seems to work

**Comment by nishandi** [comment]
@LindaSchaar that's so awesome to hear! thanks for hanging in there and helping figure it out! How are you planning to use the app? Are these your company specific stickers or just for your own use/testing?

**Comment by LindaSchaar** [comment]
@nishandi Yes offcourse no problem, thanks for your help. Yes we are using this app for company specific stickers. It is not working with GIF's? the GIF is not moving, do you know if it should be working?
