### ISSUE TITLE
Sample code for the latest Sticker app in Teams?

### ISSUE THREAD

**Issue by GauravES** [OfficeDev/microsoft-teams-stickers-app#36]
The Sticker app/messaging extension in Teams (March 2020) is different from the app described here.  Is it possible to have this code updated to match that app?   In particular, the current sticker app has a nav bar to the left of the search interface.  How does one enabled that in a messaging extension?

![image](https://user-images.githubusercontent.com/31090404/76142557-afeeb500-6023-11ea-9c86-133f8e20b72f.png)

**Comment by jotrick** [comment]
Hi @GauravES ,

Sadly, the nav bar on the left is not currently available to third party developers, so the feature cannot be added to the template.

Thank you for your question! We can take it into consideration when prioritizing new features for the future.
